name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # daily at 01:00

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          nix-options: --accept-flake-config
          token : ${{ secrets.FLAKE_TOKEN }}
          pr-title: "Update flake inputs"
          pr-labels: |
            dependencies
            automated
  mergepal-merge:
    runs-on: ubuntu-latest
    needs:
      - nix-flake-update
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@vX.Y.Z
        with:
          token: ${{ secrets.FLAKE_TOKEN }}
