name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # daily at 01:00 est
  push:
    paths:
      - 'flake.nix'
    branches:
      - main

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: [nixos]
    outputs:
      pr-number: ${{ steps.create-pr.outputs.pull-request-number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Update flake.lock
        run: |
          nix flake update --accept-flake-config --commit-lock-file

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.FLAKE_TOKEN }}
          commit-message: "flake.lock: Update"
          title: "Update flake inputs"
          body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          labels: |
            dependencies
            automated
          branch: update_flake_lock_action

  build:
    needs: nix-flake-update
    runs-on: [nixos]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build with om ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -euo pipefail
          nix run github:juspay/omnix -- ci run -- --accept-flake-config

  merge:
    needs: [nix-flake-update, build]
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: auto-merge
        if: needs.nix-flake-update.outputs.pr-number != ''
        run: gh pr merge --auto --squash ${{ needs.nix-flake-update.outputs.pr-number }}
        env:
          GH_TOKEN: ${{ secrets.FLAKE_TOKEN }}
