mergepal-merge: # run merge pal in the end
    runs-on: ubuntu-latest
    needs:
      # make sure all required jobs are listed here
      - test1-this
      - test1-that
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@vX.Y.Z
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
